openapi: 3.0.0
info:
  title: Authentication API
  description: API for user authentication and profile management in the Radiology Text Book platform
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/auth
    description: Local development server
  - url: https://api.radiology-textbook.com/auth
    description: Production server

paths:
  /register:
    post:
      summary: Register a new user
      description: Creates a new user account with the provided information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password
                name:
                  type: string
                  description: User's full name
                medical_level:
                  type: string
                  enum: [medical_student, resident, fellow, attending, other]
                  description: User's medical background level
                institution:
                  type: string
                  description: Educational institution or hospital
                specialty_interest:
                  type: string
                  description: Area of medical specialty interest
                learning_goals:
                  type: array
                  items:
                    type: string
                  description: Array of learning goals and objectives
                preferred_language:
                  type: string
                  default: "en"
                  description: Preferred language for content
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  user:
                    $ref: '#/components/schemas/User'
                  message:
                    type: string
                    example: "Registration successful. Please check your email for verification."
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: Email already in use
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /login:
    post:
      summary: Login user
      description: Authenticates user and returns session token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                remember_me:
                  type: boolean
                  default: false
                  description: Whether to extend session duration
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  token:
                    type: string
                    description: JWT token for session
                  refresh_token:
                    type: string
                    description: Refresh token for extending session
                  user:
                    $ref: '#/components/schemas/User'
                  session_id:
                    type: string
                    format: uuid
                    description: Session identifier
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /logout:
    post:
      summary: Logout user
      description: Invalidates the current session
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Logout successful"
        '401':
          description: Unauthorized - invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /profile:
    get:
      summary: Get user profile
      description: Retrieves the current user's profile information
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  profile:
                    $ref: '#/components/schemas/UserProfile'
    put:
      summary: Update user profile
      description: Updates the current user's profile information
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                medical_level:
                  type: string
                  enum: [medical_student, resident, fellow, attending, other]
                institution:
                  type: string
                specialty_interest:
                  type: string
                learning_goals:
                  type: array
                  items:
                    type: string
                preferred_language:
                  type: string
                timezone:
                  type: string
                bio:
                  type: string
                avatar_url:
                  type: string
                  format: uri
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  profile:
                    $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized - invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /profile/preferences:
    get:
      summary: Get user preferences
      description: Retrieves the current user's preferences
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Preferences retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  preferences:
                    type: object
                    additionalProperties: true
    put:
      summary: Update user preferences
      description: Updates the current user's preferences
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
              description: Key-value pairs of user preferences
      responses:
        '200':
          description: Preferences updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  preferences:
                    type: object
                    additionalProperties: true

  /forgot-password:
    post:
      summary: Request password reset
      description: Sends a password reset email to the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
      responses:
        '200':
          description: Password reset email sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Password reset email sent. Please check your inbox."
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /reset-password:
    post:
      summary: Reset password
      description: Resets the user's password using the reset token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
                - new_password
              properties:
                token:
                  type: string
                  description: Password reset token
                new_password:
                  type: string
                  format: password
                  minLength: 8
      responses:
        '200':
          description: Password reset successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Password reset successfully."
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /verify-email:
    post:
      summary: Verify email address
      description: Verifies the user's email address using the verification token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
                  description: Email verification token
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Email verified successfully."
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [student, resident, attending, admin, content_editor]
        medical_level:
          type: string
          enum: [medical_student, resident, fellow, attending, other]
        is_verified:
          type: boolean
        preferences:
          type: object
          additionalProperties: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        last_login_at:
          type: string
          format: date-time
        is_active:
          type: boolean

    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        institution:
          type: string
        specialty_interest:
          type: string
        learning_goals:
          type: array
          items:
            type: string
        preferred_language:
          type: string
          default: "en"
        timezone:
          type: string
          default: "UTC"
        bio:
          type: string
        avatar_url:
          type: string
          format: uri
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
        message:
          type: string